export const NUMBER_INCREMENT   = 'NUMBER_INCREMENT'
export const NUMBER_DECREMENT   = 'NUMBER_DECREMENT'


//Auth
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USERDATA_FROM_COOKIES = 'SET_USERDATA_FROM_COOKIES';
export const GET_USERDATA_FROM_COOKIES = 'GET_USERDATA_FROM_COOKIES';


//Table
export const SET_ALL_TABLE = 'SET_ALL_TABLE'
export const CLEAR_ALL_TABLE = 'CLEAR_ALL_TABLE'


//Location
export const SET_ALL_LOCATION_TABLE = 'SET_ALL_LOCATION_TABLE'
export const CLEAR_ALL_LOCATION_TABLE = 'CLEAR_ALL_LOCATION_TABLE'


//Socket
export const SET_SOCKET_CONNECTION = 'SET_SOCKET_CONNECTION'
