export const NUMBER_INCREMENT   = 'NUMBER_INCREMENT'
export const NUMBER_DECREMENT   = 'NUMBER_DECREMENT'


//Auth
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USERDATA_FROM_COOKIES = 'SET_USERDATA_FROM_COOKIES';
export const GET_USERDATA_FROM_COOKIES = 'GET_USERDATA_FROM_COOKIES';


//Cashier
export const GET_ALL_TABLE = 'GET_ALL_TABLE'
export const GET_ALL_LOCATION_TABLE = 'GET_ALL_LOCATION_TABLE'
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID'
