export const LOAD_TABLE = 'LOAD_TABLE'
export const LOAD_TABLE_SUCCESS = 'LOAD_TABLE_SUCCESS'
export const LOAD_TABLE_FAILURE = 'LOAD_TABLE_FAILURE'
export const SOCKET_LOAD_TABLE = 'SOCKET_LOAD_TABLE'


export const HANDLE_LOGIN = 'HANDLE_LOGIN'
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const CHECK_TOKEN = 'CHECK_TOKEN'
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS'
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE'

export const ADD_NEW_DISH = 'ADD_NEW_DISH'
export const CHANGE_AMOUNT_ORDERING = 'CHANGE_AMOUNT_ORDERING'

export const LOAD_DISH = 'LOAD_DISH'
export const LOAD_DISH_SUCCESS = 'LOAD_DISH_SUCCESS'
export const LOAD_DISH_FAILURE = 'LOAD_DISH_FAILURE'

export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER'
export const LOAD_ORDER_INFOMATION = 'LOAD_ORDER_INFOMATION'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const SAVE_ORDER = 'SAVE_ORDER'
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS'
export const SAVE_ORDER_FAILURE = 'SAVE_ORDER_FAILURE'
export const CHANGE_TOTAL_AP_ORDERING = 'CHANGE_TOTAL_AP_ORDERING'

export const LOAD_ORDERED = 'LOAD_ORDERED'
export const LOAD_ORDERED_SUCCESS = 'LOAD_ORDERED_SUCCESS'
export const LOAD_ORDERED_FAILURE = 'LOAD_ORDERED_FAILURE'

export const CHANGE_OPTION_DISH_ORDERING = 'CHANGE_OPTION_DISH_ORDERING'
export const CHANGE_TABLE_ID = 'CHANGE_TABLE_ID'
export const SAVE_ORDER_NOT_ENOUGH = 'SAVE_ORDER_NOT_ENOUGH'

export const LOAD_ORDER_DISH_RETURN = 'LOAD_ORDER_DISH_RETURN'
export const LOAD_ORDER_DISH_RETURN_SUCCESS = 'LOAD_ORDER_DISH_RETURN_SUCCESS'
export const LOAD_ORDER_DISH_RETURN_FAILURE = 'LOAD_ORDER_DISH_RETURN_FAILURE'

export const LOAD_ALL_ORDER = 'LOAD_ALL_ORDER'
export const SOCKET_LOAD_ALL_ORDER = 'SOCKET_LOAD_ALL_ORDER'
export const LOAD_ALL_ORDER_SUCCESS = 'LOAD_ALL_ORDER_SUCCESS'
export const LOAD_ALL_ORDER_FAILURE = 'LOAD_ALL_ORDER_FAILURE'

