export const LOGIN_SCREEN = 'LOGIN_SCREEN'
export const LIST_TABLE_SCREEN = 'LIST_TABLE_SCREEN'
export const ORDER_SCREEN = 'ORDER_SCREEN'
export const RETURN_DISH_SCREEN = 'RETURN_DISH_SCREEN'
export const KITCHEN_SCREEN = 'KITCHEN_SCREEN'
export const SPLASH_SCREEN = 'SPLASH_SCREEN'

export const ORDERING_SCREEN = 'ORDERING_SCREEN'
export const ORDERED_SCREEN = 'ORDERED_SCREEN'
